export {default as Header} from './Header'
export {default as Search} from './Search'
export {default as Best} from './Best'
export {default as Exclusive} from './Exclusive'
export {default as Categories} from './Categories'
